"""link shelters <-> intake_requests

Revision ID: ddb326bf0f71
Revises: 7e9d02b961e8
Create Date: 2025-09-05 22:44:23.485255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb326bf0f71'
down_revision: Union[str, None] = '7e9d02b961e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
